<?php

return [

    /**
     * List of countries indexed by their ISO 3166-1 alpha-2 country codes.
     *
     * This array provides a mapping between 2-letter country codes and their full English names.
     *
     * @var array<string, string>
     */
    'countries' => [
        'AF' => 'Afghanistan',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia, Plurinational State of',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'CV' => 'Cabo Verde',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, The Democratic Republic of the',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czechia',
        'CI' => 'Côte d`Ivoire',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'SZ' => 'Eswatini',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and McDonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People`s Republic of',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People`s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States of',
        'MD' => 'Moldova, Republic of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MK' => 'North Macedonia',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestine, State of',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'RE' => 'Réunion',
        'BL' => 'Saint Barthélemy',
        'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin (French part)',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten (Dutch part)',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan, Province of China',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania, United Republic of',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela, Bolivarian Republic of',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
        'AX' => 'Åland Islands'
    ],

    /**
     * Available datetime format options for the application.
     *
     * The keys represent PHP date format strings used for storing or formatting datetimes,
     * and the values are human-readable examples to help users understand the format.
     *
     * @var array<string, string>
     */
    'dates' => [
        'd/m/Y' => 'DD/MM/YYYY (31/12/2025)',
        'm/d/Y' => 'MM/DD/YYYY (12/31/2025)',
        'Y-m-d' => 'YYYY-MM-DD (2025-12-31)',
        'd-m-Y' => 'DD-MM-YYYY (31-12-2025)',
        'M d, Y' => 'Mon DD, YYYY (Dec 31, 2025)',
        'F d, Y' => 'Month DD, YYYY (December 31, 2025)',
        'D, d/m/Y' => 'Day, DD/MM/YYYY (Wed, 31/12/2025)',
        'D, m/d/Y' => 'Day, MM/DD/YYYY (Wed, 12/31/2025)',
        'D, M d, Y' => 'Day, Mon DD, YYYY (Wed, Dec 31, 2025)',
        'D d-m-Y' => 'Day DD-MM-YYYY (Wed 31-12-2025)',
        'l, d/m/Y' => 'Day, DD/MM/YYYY (Wednesday, 31/12/2025)',
        'l, m/d/Y' => 'Day, MM/DD/YYYY (Wednesday, 12/31/2025)',
        'l, F d, Y' => 'Day, Month DD, YYYY (Wednesday, December 31, 2025)',
        'l d F Y' => 'Day DD Month YYYY (Wednesday 31 December 2025)',
    ],

    /**
     * Available timezone options for the application.
     *
     * The keys represent PHP timezone identifiers used for timezone conversions,
     * and the values are human-readable labels showing the UTC offset and timezone name.
     *
     * @var array<string, string>
     */
    'timezones' => [
        'Pacific/Midway' => '(UTC-11) Pacific/Midway',
        'Pacific/Niue' => '(UTC-11) Pacific/Niue',
        'Pacific/Pago_Pago' => '(UTC-11) Pacific/Pago_Pago',
        'America/Adak' => '(UTC-10) America/Adak',
        'Pacific/Honolulu' => '(UTC-10) Pacific/Honolulu',
        'Pacific/Rarotonga' => '(UTC-10) Pacific/Rarotonga',
        'Pacific/Tahiti' => '(UTC-10) Pacific/Tahiti',
        'Pacific/Marquesas' => '(UTC-9:30) Pacific/Marquesas',
        'America/Anchorage' => '(UTC-9) America/Anchorage',
        'America/Juneau' => '(UTC-9) America/Juneau',
        'America/Metlakatla' => '(UTC-9) America/Metlakatla',
        'America/Nome' => '(UTC-9) America/Nome',
        'America/Sitka' => '(UTC-9) America/Sitka',
        'America/Yakutat' => '(UTC-9) America/Yakutat',
        'Pacific/Gambier' => '(UTC-9) Pacific/Gambier',
        'America/Los_Angeles' => '(UTC-8) America/Los_Angeles',
        'America/Tijuana' => '(UTC-8) America/Tijuana',
        'America/Vancouver' => '(UTC-8) America/Vancouver',
        'Pacific/Pitcairn' => '(UTC-8) Pacific/Pitcairn',
        'America/Boise' => '(UTC-7) America/Boise',
        'America/Cambridge_Bay' => '(UTC-7) America/Cambridge_Bay',
        'America/Ciudad_Juarez' => '(UTC-7) America/Ciudad_Juarez',
        'America/Creston' => '(UTC-7) America/Creston',
        'America/Dawson' => '(UTC-7) America/Dawson',
        'America/Dawson_Creek' => '(UTC-7) America/Dawson_Creek',
        'America/Denver' => '(UTC-7) America/Denver',
        'America/Edmonton' => '(UTC-7) America/Edmonton',
        'America/Fort_Nelson' => '(UTC-7) America/Fort_Nelson',
        'America/Hermosillo' => '(UTC-7) America/Hermosillo',
        'America/Inuvik' => '(UTC-7) America/Inuvik',
        'America/Mazatlan' => '(UTC-7) America/Mazatlan',
        'America/Phoenix' => '(UTC-7) America/Phoenix',
        'America/Whitehorse' => '(UTC-7) America/Whitehorse',
        'America/Bahia_Banderas' => '(UTC-6) America/Bahia_Banderas',
        'America/Belize' => '(UTC-6) America/Belize',
        'America/Chicago' => '(UTC-6) America/Chicago',
        'America/Chihuahua' => '(UTC-6) America/Chihuahua',
        'America/Costa_Rica' => '(UTC-6) America/Costa_Rica',
        'America/El_Salvador' => '(UTC-6) America/El_Salvador',
        'America/Guatemala' => '(UTC-6) America/Guatemala',
        'America/Indiana/Knox' => '(UTC-6) America/Indiana/Knox',
        'America/Indiana/Tell_City' => '(UTC-6) America/Indiana/Tell_City',
        'America/Managua' => '(UTC-6) America/Managua',
        'America/Matamoros' => '(UTC-6) America/Matamoros',
        'America/Menominee' => '(UTC-6) America/Menominee',
        'America/Merida' => '(UTC-6) America/Merida',
        'America/Mexico_City' => '(UTC-6) America/Mexico_City',
        'America/Monterrey' => '(UTC-6) America/Monterrey',
        'America/North_Dakota/Beulah' => '(UTC-6) America/North_Dakota/Beulah',
        'America/North_Dakota/Center' => '(UTC-6) America/North_Dakota/Center',
        'America/North_Dakota/New_Salem' => '(UTC-6) America/North_Dakota/New_Salem',
        'America/Ojinaga' => '(UTC-6) America/Ojinaga',
        'America/Rankin_Inlet' => '(UTC-6) America/Rankin_Inlet',
        'America/Regina' => '(UTC-6) America/Regina',
        'America/Resolute' => '(UTC-6) America/Resolute',
        'America/Swift_Current' => '(UTC-6) America/Swift_Current',
        'America/Tegucigalpa' => '(UTC-6) America/Tegucigalpa',
        'America/Winnipeg' => '(UTC-6) America/Winnipeg',
        'Pacific/Galapagos' => '(UTC-6) Pacific/Galapagos',
        'America/Atikokan' => '(UTC-5) America/Atikokan',
        'America/Bogota' => '(UTC-5) America/Bogota',
        'America/Cancun' => '(UTC-5) America/Cancun',
        'America/Cayman' => '(UTC-5) America/Cayman',
        'America/Detroit' => '(UTC-5) America/Detroit',
        'America/Eirunepe' => '(UTC-5) America/Eirunepe',
        'America/Grand_Turk' => '(UTC-5) America/Grand_Turk',
        'America/Guayaquil' => '(UTC-5) America/Guayaquil',
        'America/Havana' => '(UTC-5) America/Havana',
        'America/Indiana/Indianapolis' => '(UTC-5) America/Indiana/Indianapolis',
        'America/Indiana/Marengo' => '(UTC-5) America/Indiana/Marengo',
        'America/Indiana/Petersburg' => '(UTC-5) America/Indiana/Petersburg',
        'America/Indiana/Vevay' => '(UTC-5) America/Indiana/Vevay',
        'America/Indiana/Vincennes' => '(UTC-5) America/Indiana/Vincennes',
        'America/Indiana/Winamac' => '(UTC-5) America/Indiana/Winamac',
        'America/Iqaluit' => '(UTC-5) America/Iqaluit',
        'America/Jamaica' => '(UTC-5) America/Jamaica',
        'America/Kentucky/Louisville' => '(UTC-5) America/Kentucky/Louisville',
        'America/Kentucky/Monticello' => '(UTC-5) America/Kentucky/Monticello',
        'America/Lima' => '(UTC-5) America/Lima',
        'America/Nassau' => '(UTC-5) America/Nassau',
        'America/New_York' => '(UTC-5) America/New_York',
        'America/Panama' => '(UTC-5) America/Panama',
        'America/Port-au-Prince' => '(UTC-5) America/Port-au-Prince',
        'America/Rio_Branco' => '(UTC-5) America/Rio_Branco',
        'America/Toronto' => '(UTC-5) America/Toronto',
        'Pacific/Easter' => '(UTC-5) Pacific/Easter',
        'America/Anguilla' => '(UTC-4) America/Anguilla',
        'America/Antigua' => '(UTC-4) America/Antigua',
        'America/Aruba' => '(UTC-4) America/Aruba',
        'America/Barbados' => '(UTC-4) America/Barbados',
        'America/Blanc-Sablon' => '(UTC-4) America/Blanc-Sablon',
        'America/Boa_Vista' => '(UTC-4) America/Boa_Vista',
        'America/Campo_Grande' => '(UTC-4) America/Campo_Grande',
        'America/Caracas' => '(UTC-4) America/Caracas',
        'America/Cuiaba' => '(UTC-4) America/Cuiaba',
        'America/Curacao' => '(UTC-4) America/Curacao',
        'America/Dominica' => '(UTC-4) America/Dominica',
        'America/Glace_Bay' => '(UTC-4) America/Glace_Bay',
        'America/Goose_Bay' => '(UTC-4) America/Goose_Bay',
        'America/Grenada' => '(UTC-4) America/Grenada',
        'America/Guadeloupe' => '(UTC-4) America/Guadeloupe',
        'America/Guyana' => '(UTC-4) America/Guyana',
        'America/Halifax' => '(UTC-4) America/Halifax',
        'America/Kralendijk' => '(UTC-4) America/Kralendijk',
        'America/La_Paz' => '(UTC-4) America/La_Paz',
        'America/Lower_Princes' => '(UTC-4) America/Lower_Princes',
        'America/Manaus' => '(UTC-4) America/Manaus',
        'America/Marigot' => '(UTC-4) America/Marigot',
        'America/Martinique' => '(UTC-4) America/Martinique',
        'America/Moncton' => '(UTC-4) America/Moncton',
        'America/Montserrat' => '(UTC-4) America/Montserrat',
        'America/Port_of_Spain' => '(UTC-4) America/Port_of_Spain',
        'America/Porto_Velho' => '(UTC-4) America/Porto_Velho',
        'America/Puerto_Rico' => '(UTC-4) America/Puerto_Rico',
        'America/Santo_Domingo' => '(UTC-4) America/Santo_Domingo',
        'America/St_Barthelemy' => '(UTC-4) America/St_Barthelemy',
        'America/St_Kitts' => '(UTC-4) America/St_Kitts',
        'America/St_Lucia' => '(UTC-4) America/St_Lucia',
        'America/St_Thomas' => '(UTC-4) America/St_Thomas',
        'America/St_Vincent' => '(UTC-4) America/St_Vincent',
        'America/Thule' => '(UTC-4) America/Thule',
        'America/Tortola' => '(UTC-4) America/Tortola',
        'Atlantic/Bermuda' => '(UTC-4) Atlantic/Bermuda',
        'America/St_Johns' => '(UTC-3:30) America/St_Johns',
        'America/Araguaina' => '(UTC-3) America/Araguaina',
        'America/Argentina/Buenos_Aires' => '(UTC-3) America/Argentina/Buenos_Aires',
        'America/Argentina/Catamarca' => '(UTC-3) America/Argentina/Catamarca',
        'America/Argentina/Cordoba' => '(UTC-3) America/Argentina/Cordoba',
        'America/Argentina/Jujuy' => '(UTC-3) America/Argentina/Jujuy',
        'America/Argentina/La_Rioja' => '(UTC-3) America/Argentina/La_Rioja',
        'America/Argentina/Mendoza' => '(UTC-3) America/Argentina/Mendoza',
        'America/Argentina/Rio_Gallegos' => '(UTC-3) America/Argentina/Rio_Gallegos',
        'America/Argentina/Salta' => '(UTC-3) America/Argentina/Salta',
        'America/Argentina/San_Juan' => '(UTC-3) America/Argentina/San_Juan',
        'America/Argentina/San_Luis' => '(UTC-3) America/Argentina/San_Luis',
        'America/Argentina/Tucuman' => '(UTC-3) America/Argentina/Tucuman',
        'America/Argentina/Ushuaia' => '(UTC-3) America/Argentina/Ushuaia',
        'America/Asuncion' => '(UTC-3) America/Asuncion',
        'America/Bahia' => '(UTC-3) America/Bahia',
        'America/Belem' => '(UTC-3) America/Belem',
        'America/Cayenne' => '(UTC-3) America/Cayenne',
        'America/Fortaleza' => '(UTC-3) America/Fortaleza',
        'America/Maceio' => '(UTC-3) America/Maceio',
        'America/Miquelon' => '(UTC-3) America/Miquelon',
        'America/Montevideo' => '(UTC-3) America/Montevideo',
        'America/Paramaribo' => '(UTC-3) America/Paramaribo',
        'America/Punta_Arenas' => '(UTC-3) America/Punta_Arenas',
        'America/Recife' => '(UTC-3) America/Recife',
        'America/Santarem' => '(UTC-3) America/Santarem',
        'America/Santiago' => '(UTC-3) America/Santiago',
        'America/Sao_Paulo' => '(UTC-3) America/Sao_Paulo',
        'Antarctica/Palmer' => '(UTC-3) Antarctica/Palmer',
        'Antarctica/Rothera' => '(UTC-3) Antarctica/Rothera',
        'Atlantic/Stanley' => '(UTC-3) Atlantic/Stanley',
        'America/Noronha' => '(UTC-2) America/Noronha',
        'America/Nuuk' => '(UTC-2) America/Nuuk',
        'America/Scoresbysund' => '(UTC-2) America/Scoresbysund',
        'Atlantic/South_Georgia' => '(UTC-2) Atlantic/South_Georgia',
        'Atlantic/Azores' => '(UTC-1) Atlantic/Azores',
        'Atlantic/Cape_Verde' => '(UTC-1) Atlantic/Cape_Verde',
        'Africa/Abidjan' => '(UTC+0) Africa/Abidjan',
        'Africa/Accra' => '(UTC+0) Africa/Accra',
        'Africa/Bamako' => '(UTC+0) Africa/Bamako',
        'Africa/Banjul' => '(UTC+0) Africa/Banjul',
        'Africa/Bissau' => '(UTC+0) Africa/Bissau',
        'Africa/Conakry' => '(UTC+0) Africa/Conakry',
        'Africa/Dakar' => '(UTC+0) Africa/Dakar',
        'Africa/Freetown' => '(UTC+0) Africa/Freetown',
        'Africa/Lome' => '(UTC+0) Africa/Lome',
        'Africa/Monrovia' => '(UTC+0) Africa/Monrovia',
        'Africa/Nouakchott' => '(UTC+0) Africa/Nouakchott',
        'Africa/Ouagadougou' => '(UTC+0) Africa/Ouagadougou',
        'Africa/Sao_Tome' => '(UTC+0) Africa/Sao_Tome',
        'America/Danmarkshavn' => '(UTC+0) America/Danmarkshavn',
        'Antarctica/Troll' => '(UTC+0) Antarctica/Troll',
        'Atlantic/Canary' => '(UTC+0) Atlantic/Canary',
        'Atlantic/Faroe' => '(UTC+0) Atlantic/Faroe',
        'Atlantic/Madeira' => '(UTC+0) Atlantic/Madeira',
        'Atlantic/Reykjavik' => '(UTC+0) Atlantic/Reykjavik',
        'Atlantic/St_Helena' => '(UTC+0) Atlantic/St_Helena',
        'Europe/Dublin' => '(UTC+0) Europe/Dublin',
        'Europe/Guernsey' => '(UTC+0) Europe/Guernsey',
        'Europe/Isle_of_Man' => '(UTC+0) Europe/Isle_of_Man',
        'Europe/Jersey' => '(UTC+0) Europe/Jersey',
        'Europe/Lisbon' => '(UTC+0) Europe/Lisbon',
        'Europe/London' => '(UTC+0) Europe/London',
        'UTC' => '(UTC+0) UTC',
        'Africa/Algiers' => '(UTC+1) Africa/Algiers',
        'Africa/Bangui' => '(UTC+1) Africa/Bangui',
        'Africa/Brazzaville' => '(UTC+1) Africa/Brazzaville',
        'Africa/Casablanca' => '(UTC+1) Africa/Casablanca',
        'Africa/Ceuta' => '(UTC+1) Africa/Ceuta',
        'Africa/Douala' => '(UTC+1) Africa/Douala',
        'Africa/El_Aaiun' => '(UTC+1) Africa/El_Aaiun',
        'Africa/Kinshasa' => '(UTC+1) Africa/Kinshasa',
        'Africa/Lagos' => '(UTC+1) Africa/Lagos',
        'Africa/Libreville' => '(UTC+1) Africa/Libreville',
        'Africa/Luanda' => '(UTC+1) Africa/Luanda',
        'Africa/Malabo' => '(UTC+1) Africa/Malabo',
        'Africa/Ndjamena' => '(UTC+1) Africa/Ndjamena',
        'Africa/Niamey' => '(UTC+1) Africa/Niamey',
        'Africa/Porto-Novo' => '(UTC+1) Africa/Porto-Novo',
        'Africa/Tunis' => '(UTC+1) Africa/Tunis',
        'Arctic/Longyearbyen' => '(UTC+1) Arctic/Longyearbyen',
        'Europe/Amsterdam' => '(UTC+1) Europe/Amsterdam',
        'Europe/Andorra' => '(UTC+1) Europe/Andorra',
        'Europe/Belgrade' => '(UTC+1) Europe/Belgrade',
        'Europe/Berlin' => '(UTC+1) Europe/Berlin',
        'Europe/Bratislava' => '(UTC+1) Europe/Bratislava',
        'Europe/Brussels' => '(UTC+1) Europe/Brussels',
        'Europe/Budapest' => '(UTC+1) Europe/Budapest',
        'Europe/Busingen' => '(UTC+1) Europe/Busingen',
        'Europe/Copenhagen' => '(UTC+1) Europe/Copenhagen',
        'Europe/Gibraltar' => '(UTC+1) Europe/Gibraltar',
        'Europe/Ljubljana' => '(UTC+1) Europe/Ljubljana',
        'Europe/Luxembourg' => '(UTC+1) Europe/Luxembourg',
        'Europe/Madrid' => '(UTC+1) Europe/Madrid',
        'Europe/Malta' => '(UTC+1) Europe/Malta',
        'Europe/Monaco' => '(UTC+1) Europe/Monaco',
        'Europe/Oslo' => '(UTC+1) Europe/Oslo',
        'Europe/Paris' => '(UTC+1) Europe/Paris',
        'Europe/Podgorica' => '(UTC+1) Europe/Podgorica',
        'Europe/Prague' => '(UTC+1) Europe/Prague',
        'Europe/Rome' => '(UTC+1) Europe/Rome',
        'Europe/San_Marino' => '(UTC+1) Europe/San_Marino',
        'Europe/Sarajevo' => '(UTC+1) Europe/Sarajevo',
        'Europe/Skopje' => '(UTC+1) Europe/Skopje',
        'Europe/Stockholm' => '(UTC+1) Europe/Stockholm',
        'Europe/Tirane' => '(UTC+1) Europe/Tirane',
        'Europe/Vaduz' => '(UTC+1) Europe/Vaduz',
        'Europe/Vatican' => '(UTC+1) Europe/Vatican',
        'Europe/Vienna' => '(UTC+1) Europe/Vienna',
        'Europe/Warsaw' => '(UTC+1) Europe/Warsaw',
        'Europe/Zagreb' => '(UTC+1) Europe/Zagreb',
        'Europe/Zurich' => '(UTC+1) Europe/Zurich',
        'Africa/Blantyre' => '(UTC+2) Africa/Blantyre',
        'Africa/Bujumbura' => '(UTC+2) Africa/Bujumbura',
        'Africa/Cairo' => '(UTC+2) Africa/Cairo',
        'Africa/Gaborone' => '(UTC+2) Africa/Gaborone',
        'Africa/Harare' => '(UTC+2) Africa/Harare',
        'Africa/Johannesburg' => '(UTC+2) Africa/Johannesburg',
        'Africa/Juba' => '(UTC+2) Africa/Juba',
        'Africa/Khartoum' => '(UTC+2) Africa/Khartoum',
        'Africa/Kigali' => '(UTC+2) Africa/Kigali',
        'Africa/Lubumbashi' => '(UTC+2) Africa/Lubumbashi',
        'Africa/Lusaka' => '(UTC+2) Africa/Lusaka',
        'Africa/Maputo' => '(UTC+2) Africa/Maputo',
        'Africa/Maseru' => '(UTC+2) Africa/Maseru',
        'Africa/Mbabane' => '(UTC+2) Africa/Mbabane',
        'Africa/Tripoli' => '(UTC+2) Africa/Tripoli',
        'Africa/Windhoek' => '(UTC+2) Africa/Windhoek',
        'Asia/Beirut' => '(UTC+2) Asia/Beirut',
        'Asia/Famagusta' => '(UTC+2) Asia/Famagusta',
        'Asia/Gaza' => '(UTC+2) Asia/Gaza',
        'Asia/Hebron' => '(UTC+2) Asia/Hebron',
        'Asia/Jerusalem' => '(UTC+2) Asia/Jerusalem',
        'Asia/Nicosia' => '(UTC+2) Asia/Nicosia',
        'Europe/Athens' => '(UTC+2) Europe/Athens',
        'Europe/Bucharest' => '(UTC+2) Europe/Bucharest',
        'Europe/Chisinau' => '(UTC+2) Europe/Chisinau',
        'Europe/Helsinki' => '(UTC+2) Europe/Helsinki',
        'Europe/Kaliningrad' => '(UTC+2) Europe/Kaliningrad',
        'Europe/Kyiv' => '(UTC+2) Europe/Kyiv',
        'Europe/Mariehamn' => '(UTC+2) Europe/Mariehamn',
        'Europe/Riga' => '(UTC+2) Europe/Riga',
        'Europe/Sofia' => '(UTC+2) Europe/Sofia',
        'Europe/Tallinn' => '(UTC+2) Europe/Tallinn',
        'Europe/Vilnius' => '(UTC+2) Europe/Vilnius',
        'Africa/Addis_Ababa' => '(UTC+3) Africa/Addis_Ababa',
        'Africa/Asmara' => '(UTC+3) Africa/Asmara',
        'Africa/Dar_es_Salaam' => '(UTC+3) Africa/Dar_es_Salaam',
        'Africa/Djibouti' => '(UTC+3) Africa/Djibouti',
        'Africa/Kampala' => '(UTC+3) Africa/Kampala',
        'Africa/Mogadishu' => '(UTC+3) Africa/Mogadishu',
        'Africa/Nairobi' => '(UTC+3) Africa/Nairobi',
        'Antarctica/Syowa' => '(UTC+3) Antarctica/Syowa',
        'Asia/Aden' => '(UTC+3) Asia/Aden',
        'Asia/Amman' => '(UTC+3) Asia/Amman',
        'Asia/Baghdad' => '(UTC+3) Asia/Baghdad',
        'Asia/Bahrain' => '(UTC+3) Asia/Bahrain',
        'Asia/Damascus' => '(UTC+3) Asia/Damascus',
        'Asia/Kuwait' => '(UTC+3) Asia/Kuwait',
        'Asia/Qatar' => '(UTC+3) Asia/Qatar',
        'Asia/Riyadh' => '(UTC+3) Asia/Riyadh',
        'Europe/Istanbul' => '(UTC+3) Europe/Istanbul',
        'Europe/Kirov' => '(UTC+3) Europe/Kirov',
        'Europe/Minsk' => '(UTC+3) Europe/Minsk',
        'Europe/Moscow' => '(UTC+3) Europe/Moscow',
        'Europe/Simferopol' => '(UTC+3) Europe/Simferopol',
        'Europe/Volgograd' => '(UTC+3) Europe/Volgograd',
        'Indian/Antananarivo' => '(UTC+3) Indian/Antananarivo',
        'Indian/Comoro' => '(UTC+3) Indian/Comoro',
        'Indian/Mayotte' => '(UTC+3) Indian/Mayotte',
        'Asia/Tehran' => '(UTC+3:30) Asia/Tehran',
        'Asia/Baku' => '(UTC+4) Asia/Baku',
        'Asia/Dubai' => '(UTC+4) Asia/Dubai',
        'Asia/Muscat' => '(UTC+4) Asia/Muscat',
        'Asia/Tbilisi' => '(UTC+4) Asia/Tbilisi',
        'Asia/Yerevan' => '(UTC+4) Asia/Yerevan',
        'Europe/Astrakhan' => '(UTC+4) Europe/Astrakhan',
        'Europe/Samara' => '(UTC+4) Europe/Samara',
        'Europe/Saratov' => '(UTC+4) Europe/Saratov',
        'Europe/Ulyanovsk' => '(UTC+4) Europe/Ulyanovsk',
        'Indian/Mahe' => '(UTC+4) Indian/Mahe',
        'Indian/Mauritius' => '(UTC+4) Indian/Mauritius',
        'Indian/Reunion' => '(UTC+4) Indian/Reunion',
        'Asia/Kabul' => '(UTC+4:30) Asia/Kabul',
        'Antarctica/Mawson' => '(UTC+5) Antarctica/Mawson',
        'Antarctica/Vostok' => '(UTC+5) Antarctica/Vostok',
        'Asia/Almaty' => '(UTC+5) Asia/Almaty',
        'Asia/Aqtau' => '(UTC+5) Asia/Aqtau',
        'Asia/Aqtobe' => '(UTC+5) Asia/Aqtobe',
        'Asia/Ashgabat' => '(UTC+5) Asia/Ashgabat',
        'Asia/Atyrau' => '(UTC+5) Asia/Atyrau',
        'Asia/Dushanbe' => '(UTC+5) Asia/Dushanbe',
        'Asia/Karachi' => '(UTC+5) Asia/Karachi',
        'Asia/Oral' => '(UTC+5) Asia/Oral',
        'Asia/Qostanay' => '(UTC+5) Asia/Qostanay',
        'Asia/Qyzylorda' => '(UTC+5) Asia/Qyzylorda',
        'Asia/Samarkand' => '(UTC+5) Asia/Samarkand',
        'Asia/Tashkent' => '(UTC+5) Asia/Tashkent',
        'Asia/Yekaterinburg' => '(UTC+5) Asia/Yekaterinburg',
        'Indian/Kerguelen' => '(UTC+5) Indian/Kerguelen',
        'Indian/Maldives' => '(UTC+5) Indian/Maldives',
        'Asia/Colombo' => '(UTC+5:30) Asia/Colombo',
        'Asia/Kolkata' => '(UTC+5:30) Asia/Kolkata',
        'Asia/Kathmandu' => '(UTC+5:45) Asia/Kathmandu',
        'Asia/Bishkek' => '(UTC+6) Asia/Bishkek',
        'Asia/Dhaka' => '(UTC+6) Asia/Dhaka',
        'Asia/Omsk' => '(UTC+6) Asia/Omsk',
        'Asia/Thimphu' => '(UTC+6) Asia/Thimphu',
        'Asia/Urumqi' => '(UTC+6) Asia/Urumqi',
        'Indian/Chagos' => '(UTC+6) Indian/Chagos',
        'Asia/Yangon' => '(UTC+6:30) Asia/Yangon',
        'Indian/Cocos' => '(UTC+6:30) Indian/Cocos',
        'Antarctica/Davis' => '(UTC+7) Antarctica/Davis',
        'Asia/Bangkok' => '(UTC+7) Asia/Bangkok',
        'Asia/Barnaul' => '(UTC+7) Asia/Barnaul',
        'Asia/Ho_Chi_Minh' => '(UTC+7) Asia/Ho_Chi_Minh',
        'Asia/Hovd' => '(UTC+7) Asia/Hovd',
        'Asia/Jakarta' => '(UTC+7) Asia/Jakarta',
        'Asia/Krasnoyarsk' => '(UTC+7) Asia/Krasnoyarsk',
        'Asia/Novokuznetsk' => '(UTC+7) Asia/Novokuznetsk',
        'Asia/Novosibirsk' => '(UTC+7) Asia/Novosibirsk',
        'Asia/Phnom_Penh' => '(UTC+7) Asia/Phnom_Penh',
        'Asia/Pontianak' => '(UTC+7) Asia/Pontianak',
        'Asia/Tomsk' => '(UTC+7) Asia/Tomsk',
        'Asia/Vientiane' => '(UTC+7) Asia/Vientiane',
        'Indian/Christmas' => '(UTC+7) Indian/Christmas',
        'Asia/Brunei' => '(UTC+8) Asia/Brunei',
        'Asia/Choibalsan' => '(UTC+8) Asia/Choibalsan',
        'Asia/Hong_Kong' => '(UTC+8) Asia/Hong_Kong',
        'Asia/Irkutsk' => '(UTC+8) Asia/Irkutsk',
        'Asia/Kuala_Lumpur' => '(UTC+8) Asia/Kuala_Lumpur',
        'Asia/Kuching' => '(UTC+8) Asia/Kuching',
        'Asia/Macau' => '(UTC+8) Asia/Macau',
        'Asia/Makassar' => '(UTC+8) Asia/Makassar',
        'Asia/Manila' => '(UTC+8) Asia/Manila',
        'Asia/Shanghai' => '(UTC+8) Asia/Shanghai',
        'Asia/Singapore' => '(UTC+8) Asia/Singapore',
        'Asia/Taipei' => '(UTC+8) Asia/Taipei',
        'Asia/Ulaanbaatar' => '(UTC+8) Asia/Ulaanbaatar',
        'Australia/Perth' => '(UTC+8) Australia/Perth',
        'Australia/Eucla' => '(UTC+8:45) Australia/Eucla',
        'Asia/Chita' => '(UTC+9) Asia/Chita',
        'Asia/Dili' => '(UTC+9) Asia/Dili',
        'Asia/Jayapura' => '(UTC+9) Asia/Jayapura',
        'Asia/Khandyga' => '(UTC+9) Asia/Khandyga',
        'Asia/Pyongyang' => '(UTC+9) Asia/Pyongyang',
        'Asia/Seoul' => '(UTC+9) Asia/Seoul',
        'Asia/Tokyo' => '(UTC+9) Asia/Tokyo',
        'Asia/Yakutsk' => '(UTC+9) Asia/Yakutsk',
        'Pacific/Palau' => '(UTC+9) Pacific/Palau',
        'Australia/Adelaide' => '(UTC+9:30) Australia/Adelaide',
        'Australia/Broken_Hill' => '(UTC+9:30) Australia/Broken_Hill',
        'Australia/Darwin' => '(UTC+9:30) Australia/Darwin',
        'Antarctica/DumontDUrville' => '(UTC+10) Antarctica/DumontDUrville',
        'Antarctica/Macquarie' => '(UTC+10) Antarctica/Macquarie',
        'Asia/Ust-Nera' => '(UTC+10) Asia/Ust-Nera',
        'Asia/Vladivostok' => '(UTC+10) Asia/Vladivostok',
        'Australia/Brisbane' => '(UTC+10) Australia/Brisbane',
        'Australia/Hobart' => '(UTC+10) Australia/Hobart',
        'Australia/Lindeman' => '(UTC+10) Australia/Lindeman',
        'Australia/Melbourne' => '(UTC+10) Australia/Melbourne',
        'Australia/Sydney' => '(UTC+10) Australia/Sydney',
        'Pacific/Chuuk' => '(UTC+10) Pacific/Chuuk',
        'Pacific/Guam' => '(UTC+10) Pacific/Guam',
        'Pacific/Port_Moresby' => '(UTC+10) Pacific/Port_Moresby',
        'Pacific/Saipan' => '(UTC+10) Pacific/Saipan',
        'Australia/Lord_Howe' => '(UTC+10:30) Australia/Lord_Howe',
        'Antarctica/Casey' => '(UTC+11) Antarctica/Casey',
        'Asia/Magadan' => '(UTC+11) Asia/Magadan',
        'Asia/Sakhalin' => '(UTC+11) Asia/Sakhalin',
        'Asia/Srednekolymsk' => '(UTC+11) Asia/Srednekolymsk',
        'Pacific/Bougainville' => '(UTC+11) Pacific/Bougainville',
        'Pacific/Efate' => '(UTC+11) Pacific/Efate',
        'Pacific/Guadalcanal' => '(UTC+11) Pacific/Guadalcanal',
        'Pacific/Kosrae' => '(UTC+11) Pacific/Kosrae',
        'Pacific/Norfolk' => '(UTC+11) Pacific/Norfolk',
        'Pacific/Noumea' => '(UTC+11) Pacific/Noumea',
        'Pacific/Pohnpei' => '(UTC+11) Pacific/Pohnpei',
        'Antarctica/McMurdo' => '(UTC+12) Antarctica/McMurdo',
        'Asia/Anadyr' => '(UTC+12) Asia/Anadyr',
        'Asia/Kamchatka' => '(UTC+12) Asia/Kamchatka',
        'Pacific/Auckland' => '(UTC+12) Pacific/Auckland',
        'Pacific/Fiji' => '(UTC+12) Pacific/Fiji',
        'Pacific/Funafuti' => '(UTC+12) Pacific/Funafuti',
        'Pacific/Kwajalein' => '(UTC+12) Pacific/Kwajalein',
        'Pacific/Majuro' => '(UTC+12) Pacific/Majuro',
        'Pacific/Nauru' => '(UTC+12) Pacific/Nauru',
        'Pacific/Tarawa' => '(UTC+12) Pacific/Tarawa',
        'Pacific/Wake' => '(UTC+12) Pacific/Wake',
        'Pacific/Wallis' => '(UTC+12) Pacific/Wallis',
        'Pacific/Chatham' => '(UTC+12:45) Pacific/Chatham',
        'Pacific/Apia' => '(UTC+13) Pacific/Apia',
        'Pacific/Fakaofo' => '(UTC+13) Pacific/Fakaofo',
        'Pacific/Kanton' => '(UTC+13) Pacific/Kanton',
        'Pacific/Tongatapu' => '(UTC+13) Pacific/Tongatapu',
        'Pacific/Kiritimati' => '(UTC+14) Pacific/Kiritimati',
    ],

    /**
     * Available avatar provider options.
     *
     * Each entry contains:
     *   - label       : Human-readable name shown in the admin dropdown.
     *   - url         : URL pattern. Use {seed} for the user's email (consistent),
     *                   {md5} for md5-hashed email, and {name} for URL-encoded fullname.
     *   - manage_url  : (optional) External URL users can visit to manage/change their avatar.
     *                   If null, the "Change Avatar" button is hidden on the client settings page.
     *
     * @var array<string, array>
     */
    'avatar_providers' => [
        'gravatar' => [
            'label'      => 'Gravatar',
            'url'        => 'https://www.gravatar.com/avatar/{md5}?s=128&d=mp',
            'manage_url' => 'https://gravatar.com/emails',
        ],
        'ui-avatars' => [
            'label'      => 'UI Avatars (Initials)',
            'url'        => 'https://ui-avatars.com/api/?name={name}&background=random&size=128',
            'manage_url' => null,
        ],
        'dicebear-fun-emoji' => [
            'label'      => 'DiceBear Fun Emoji',
            'url'        => 'https://api.dicebear.com/9.x/fun-emoji/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-thumbs' => [
            'label'      => 'DiceBear Thumbs',
            'url'        => 'https://api.dicebear.com/9.x/thumbs/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-bottts' => [
            'label'      => 'DiceBear Bottts (Robots)',
            'url'        => 'https://api.dicebear.com/9.x/bottts/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-bottts-neutral' => [
            'label'      => 'DiceBear Bottts Neutral',
            'url'        => 'https://api.dicebear.com/9.x/bottts-neutral/svg?seed={seed}',
            'manage_url' => null,
        ],
        'robohash' => [
            'label'      => 'Robohash (Monsters/Robots)',
            'url'        => 'https://robohash.org/{md5}?set=set1&size=128x128',
            'manage_url' => null,
        ],
        'robohash-monsters' => [
            'label'      => 'Robohash Monsters',
            'url'        => 'https://robohash.org/{md5}?set=set2&size=128x128',
            'manage_url' => null,
        ],
        'dicebear-identicon' => [
            'label'      => 'DiceBear Identicon',
            'url'        => 'https://api.dicebear.com/9.x/identicon/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-shapes' => [
            'label'      => 'DiceBear Shapes',
            'url'        => 'https://api.dicebear.com/9.x/shapes/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-rings' => [
            'label'      => 'DiceBear Rings',
            'url'        => 'https://api.dicebear.com/9.x/rings/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-glass' => [
            'label'      => 'DiceBear Glass',
            'url'        => 'https://api.dicebear.com/9.x/glass/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-croodles' => [
            'label'      => 'DiceBear Croodles (Doodles)',
            'url'        => 'https://api.dicebear.com/9.x/croodles/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-croodles-neutral' => [
            'label'      => 'DiceBear Croodles Neutral',
            'url'        => 'https://api.dicebear.com/9.x/croodles-neutral/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-notionists' => [
            'label'      => 'DiceBear Notionists',
            'url'        => 'https://api.dicebear.com/9.x/notionists/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-notionists-neutral' => [
            'label'      => 'DiceBear Notionists Neutral',
            'url'        => 'https://api.dicebear.com/9.x/notionists-neutral/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-pixel-art' => [
            'label'      => 'DiceBear Pixel Art',
            'url'        => 'https://api.dicebear.com/9.x/pixel-art/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-pixel-art-neutral' => [
            'label'      => 'DiceBear Pixel Art Neutral',
            'url'        => 'https://api.dicebear.com/9.x/pixel-art-neutral/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-lorelei' => [
            'label'      => 'DiceBear Lorelei',
            'url'        => 'https://api.dicebear.com/9.x/lorelei/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-micah' => [
            'label'      => 'DiceBear Micah',
            'url'        => 'https://api.dicebear.com/9.x/micah/svg?seed={seed}',
            'manage_url' => null,
        ],
        'dicebear-avataaars' => [
            'label'      => 'DiceBear Avataaars',
            'url'        => 'https://api.dicebear.com/9.x/avataaars/svg?seed={seed}',
            'manage_url' => null,
        ],
    ],
];